### ISSUE TITLE
Error while checking mail from the UI.

### ISSUE THREAD

**Issue by tdcaseware** [ruffrey/mailsac#22]
I installed mailsac on Ubuntu 16.04. But when I am running  node app from the terminal and trying to access the UI in 3000 port I am getting the following error message.(mailsac UI works, but no smtp ports are showing).

qatest@ubuntu:/$ cd opt/mailsac
qatest@ubuntu:/opt/mailsac$ node app
GET / 304 692.592 ms - -
GET /js/mailsac.js 304 10.934 ms - -
TypeError: /opt/mailsac/views/layout.jade:42
    40|         
    41|         //- Plugin includes
  > 42|         each addon in includes.head
    43|             != renderFile(addon, locals)
    44|             
    45|     body

Cannot read property 'head' of undefined
    at eval (eval at <anonymous> (/opt/mailsac/node_modules/jade/lib/index.js:218:8), <anonymous>:159:23)
    at eval (eval at <anonymous> (/opt/mailsac/node_modules/jade/lib/index.js:218:8), <anonymous>:185:4)
    at eval (eval at <anonymous> (/opt/mailsac/node_modules/jade/lib/index.js:218:8), <anonymous>:533:22)
    at res (/opt/mailsac/node_modules/jade/lib/index.js:219:38)
    at Object.exports.renderFile (/opt/mailsac/node_modules/jade/lib/index.js:380:38)
    at Object.exports.renderFile (/opt/mailsac/node_modules/jade/lib/index.js:370:21)
    at View.exports.__express [as engine] (/opt/mailsac/node_modules/jade/lib/index.js:417:11)
    at View.render (/opt/mailsac/node_modules/express/lib/view.js:126:8)
    at tryRender (/opt/mailsac/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/opt/mailsac/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/opt/mailsac/node_modules/express/lib/response.js:961:7)
    at exports.errorHandler (/opt/mailsac/lib/middleware.js:102:13)
    at Layer.handle_error (/opt/mailsac/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/opt/mailsac/node_modules/express/lib/router/index.js:310:13)
    at /opt/mailsac/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/mailsac/node_modules/express/lib/router/index.js:330:12)
---------------------------------------------
    at IncomingMessage.next (/opt/mailsac/node_modules/express/lib/router/index.js:198:7)
    at done (/opt/mailsac/node_modules/express/lib/response.js:956:25)
    at Object.exports.renderFile (/opt/mailsac/node_modules/jade/lib/index.js:372:14)
    at View.exports.__express [as engine] (/opt/mailsac/node_modules/jade/lib/index.js:417:11)
    at View.render (/opt/mailsac/node_modules/express/lib/view.js:126:8)
    at tryRender (/opt/mailsac/node_modules/express/lib/application.js:639:10)
    at EventEmitter.render (/opt/mailsac/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/opt/mailsac/node_modules/express/lib/response.js:961:7)
    at exports.errorHandler (/opt/mailsac/lib/middleware.js:102:13)
    at Layer.handle_error (/opt/mailsac/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/opt/mailsac/node_modules/express/lib/router/index.js:310:13)
    at /opt/mailsac/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/mailsac/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/mailsac/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/opt/mailsac/node_modules/express/lib/router/layer.js:67:12)
GET /css/style.css 500 1209.653 ms - -

How do I resolve the issue?

**Comment by ruffrey** [comment]
Hey, here are a few things to try:
- remove the folder `plugins/example.plugin` or set [disablePlugins](https://github.com/ruffrey/mailsac/blob/master/config/default.json#L6) to `true`
- run with environment var `DEBUG=mailsac*` to see if you get more output

Also make sure:
- run with sudo, root, or create a user that has permissions for ports 25 and 587

**Comment by ruffrey** [comment]
also, i have an updated version but need to do some work to clean it up before putting on a public branch. sorry, the code has rotted a little.

**Comment by tdcaseware** [comment]
Thanks for the prompt reply. I will try your instructions.

**Comment by ruffrey** [comment]
Did you get this working? I am closing for now, but feel free to reopen the issue if it is not fixed.

Also, @tdcaseware are you the one who is load testing mailsac.com with emails from `donotreply@test.caseware.com`? I think we have hit a few million emails received 😸

**Comment by tdcaseware** [comment]
Thanks @ruffrey , sudo nope app resolved the issue for me. You can go ahead and close this.
And I am not the person sending emails to mailsac. :smile:

**Comment by ruffrey** [comment]
Awesome! Good luck.

I mentioned it because I am considering either blocking them or rate limiting..It's rare to do that, but we are talking tens of gigabytes of traffic. Nobody has responded to my inquiries...Glad someone is using it, but they should kick down for an enterprise license..!
